// <auto-generated />
namespace WishListManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TestIfItsWork : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestIfItsWork));
        
        string IMigrationMetadata.Id
        {
            get { return "202303121032427_Test-If-Its-Work"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
